// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AccessControlInitParameters struct {

	// The list of command category rules for this managed database user.
	// +listType=set
	ACLCategories []*string `json:"aclCategories,omitempty" tf:"acl_categories,omitempty"`

	// The list of publish/subscribe channel patterns for this managed database user.
	// +listType=set
	ACLChannels []*string `json:"aclChannels,omitempty" tf:"acl_channels,omitempty"`

	// The list of individual command rules for this managed database user.
	// +listType=set
	ACLCommands []*string `json:"aclCommands,omitempty" tf:"acl_commands,omitempty"`

	// The list of access rules for this managed database user.
	// +listType=set
	ACLKeys []*string `json:"aclKeys,omitempty" tf:"acl_keys,omitempty"`
}

type AccessControlObservation struct {

	// The list of command category rules for this managed database user.
	// +listType=set
	ACLCategories []*string `json:"aclCategories,omitempty" tf:"acl_categories,omitempty"`

	// The list of publish/subscribe channel patterns for this managed database user.
	// +listType=set
	ACLChannels []*string `json:"aclChannels,omitempty" tf:"acl_channels,omitempty"`

	// The list of individual command rules for this managed database user.
	// +listType=set
	ACLCommands []*string `json:"aclCommands,omitempty" tf:"acl_commands,omitempty"`

	// The list of access rules for this managed database user.
	// +listType=set
	ACLKeys []*string `json:"aclKeys,omitempty" tf:"acl_keys,omitempty"`
}

type AccessControlParameters struct {

	// The list of command category rules for this managed database user.
	// +kubebuilder:validation:Optional
	// +listType=set
	ACLCategories []*string `json:"aclCategories" tf:"acl_categories,omitempty"`

	// The list of publish/subscribe channel patterns for this managed database user.
	// +kubebuilder:validation:Optional
	// +listType=set
	ACLChannels []*string `json:"aclChannels" tf:"acl_channels,omitempty"`

	// The list of individual command rules for this managed database user.
	// +kubebuilder:validation:Optional
	// +listType=set
	ACLCommands []*string `json:"aclCommands" tf:"acl_commands,omitempty"`

	// The list of access rules for this managed database user.
	// +kubebuilder:validation:Optional
	// +listType=set
	ACLKeys []*string `json:"aclKeys" tf:"acl_keys,omitempty"`
}

type UserInitParameters struct {
	AccessControl []AccessControlInitParameters `json:"accessControl,omitempty" tf:"access_control,omitempty"`

	// The managed database ID you want to attach this user to.
	DatabaseID *string `json:"databaseId,omitempty" tf:"database_id,omitempty"`

	// The encryption type of the new managed database user's password (MySQL engine types only - caching_sha2_password, mysql_native_password).
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// The password of the new managed database user.
	Password *string `json:"password,omitempty" tf:"password,omitempty"`

	// The permission level for the database user (Kafka engine types only - admin, read, write, readwrite).
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// The username of the new managed database user.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserObservation struct {
	AccessCert *string `json:"accessCert,omitempty" tf:"access_cert,omitempty"`

	AccessControl []AccessControlObservation `json:"accessControl,omitempty" tf:"access_control,omitempty"`

	AccessKey *string `json:"accessKey,omitempty" tf:"access_key,omitempty"`

	// The managed database ID you want to attach this user to.
	DatabaseID *string `json:"databaseId,omitempty" tf:"database_id,omitempty"`

	// The encryption type of the new managed database user's password (MySQL engine types only - caching_sha2_password, mysql_native_password).
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The password of the new managed database user.
	Password *string `json:"password,omitempty" tf:"password,omitempty"`

	// The permission level for the database user (Kafka engine types only - admin, read, write, readwrite).
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// The username of the new managed database user.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserParameters struct {

	// +kubebuilder:validation:Optional
	AccessControl []AccessControlParameters `json:"accessControl,omitempty" tf:"access_control,omitempty"`

	// The managed database ID you want to attach this user to.
	// +kubebuilder:validation:Optional
	DatabaseID *string `json:"databaseId,omitempty" tf:"database_id,omitempty"`

	// The encryption type of the new managed database user's password (MySQL engine types only - caching_sha2_password, mysql_native_password).
	// +kubebuilder:validation:Optional
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// The password of the new managed database user.
	// +kubebuilder:validation:Optional
	Password *string `json:"password,omitempty" tf:"password,omitempty"`

	// The permission level for the database user (Kafka engine types only - admin, read, write, readwrite).
	// +kubebuilder:validation:Optional
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// The username of the new managed database user.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API. Provides a Vultr database user resource. This can be used to create, read, modify, and delete users for a managed database on your Vultr account.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vultr}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.databaseId) || (has(self.initProvider) && has(self.initProvider.databaseId))",message="spec.forProvider.databaseId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
