apiVersion: vultr.vultr.upbound.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: vultr/v1alpha1/loadbalancer
  labels:
    testing.upbound.io/example-name: lb
  name: lb
spec:
  forProvider:
    balancingAlgorithm: roundrobin
    forwardingRules:
    - backendPort: 81
      backendProtocol: http
      frontendPort: 82
      frontendProtocol: http
    healthCheck:
    - checkInterval: 3
      healthyThreshold: 4
      path: /test
      port: "8080"
      protocol: http
      responseTimeout: 1
      unhealthyThreshold: 2
    label: vultr-load-balancer
    region: ewr

---

