apiVersion: vultr.vultr.upbound.io/v1alpha1
kind: ObjectStorage
metadata:
  annotations:
    meta.upbound.io/example-id: vultr/v1alpha1/objectstorage
  labels:
    testing.upbound.io/example-name: tf
  name: tf
spec:
  forProvider:
    clusterId: 2
    label: vultr-object-storage

---

