//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupsScheduleInitParameters) DeepCopyInto(out *BackupsScheduleInitParameters) {
	*out = *in
	if in.Dom != nil {
		in, out := &in.Dom, &out.Dom
		*out = new(float64)
		**out = **in
	}
	if in.Dow != nil {
		in, out := &in.Dow, &out.Dow
		*out = new(float64)
		**out = **in
	}
	if in.Hour != nil {
		in, out := &in.Hour, &out.Hour
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupsScheduleInitParameters.
func (in *BackupsScheduleInitParameters) DeepCopy() *BackupsScheduleInitParameters {
	if in == nil {
		return nil
	}
	out := new(BackupsScheduleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupsScheduleObservation) DeepCopyInto(out *BackupsScheduleObservation) {
	*out = *in
	if in.Dom != nil {
		in, out := &in.Dom, &out.Dom
		*out = new(float64)
		**out = **in
	}
	if in.Dow != nil {
		in, out := &in.Dow, &out.Dow
		*out = new(float64)
		**out = **in
	}
	if in.Hour != nil {
		in, out := &in.Hour, &out.Hour
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupsScheduleObservation.
func (in *BackupsScheduleObservation) DeepCopy() *BackupsScheduleObservation {
	if in == nil {
		return nil
	}
	out := new(BackupsScheduleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupsScheduleParameters) DeepCopyInto(out *BackupsScheduleParameters) {
	*out = *in
	if in.Dom != nil {
		in, out := &in.Dom, &out.Dom
		*out = new(float64)
		**out = **in
	}
	if in.Dow != nil {
		in, out := &in.Dow, &out.Dow
		*out = new(float64)
		**out = **in
	}
	if in.Hour != nil {
		in, out := &in.Hour, &out.Hour
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupsScheduleParameters.
func (in *BackupsScheduleParameters) DeepCopy() *BackupsScheduleParameters {
	if in == nil {
		return nil
	}
	out := new(BackupsScheduleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance) DeepCopyInto(out *Instance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Instance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceInitParameters) DeepCopyInto(out *InstanceInitParameters) {
	*out = *in
	if in.ActivationEmail != nil {
		in, out := &in.ActivationEmail, &out.ActivationEmail
		*out = new(bool)
		**out = **in
	}
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(float64)
		**out = **in
	}
	if in.AppVariables != nil {
		in, out := &in.AppVariables, &out.AppVariables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Backups != nil {
		in, out := &in.Backups, &out.Backups
		*out = new(string)
		**out = **in
	}
	if in.BackupsSchedule != nil {
		in, out := &in.BackupsSchedule, &out.BackupsSchedule
		*out = make([]BackupsScheduleInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DdosProtection != nil {
		in, out := &in.DdosProtection, &out.DdosProtection
		*out = new(bool)
		**out = **in
	}
	if in.DisablePublicIPv4 != nil {
		in, out := &in.DisablePublicIPv4, &out.DisablePublicIPv4
		*out = new(bool)
		**out = **in
	}
	if in.EnableIPv6 != nil {
		in, out := &in.EnableIPv6, &out.EnableIPv6
		*out = new(bool)
		**out = **in
	}
	if in.FirewallGroupID != nil {
		in, out := &in.FirewallGroupID, &out.FirewallGroupID
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.IpxeChainURL != nil {
		in, out := &in.IpxeChainURL, &out.IpxeChainURL
		*out = new(string)
		**out = **in
	}
	if in.IsoID != nil {
		in, out := &in.IsoID, &out.IsoID
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.OsID != nil {
		in, out := &in.OsID, &out.OsID
		*out = new(float64)
		**out = **in
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReservedIPID != nil {
		in, out := &in.ReservedIPID, &out.ReservedIPID
		*out = new(string)
		**out = **in
	}
	if in.SSHKeyIds != nil {
		in, out := &in.SSHKeyIds, &out.SSHKeyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ScriptID != nil {
		in, out := &in.ScriptID, &out.ScriptID
		*out = new(string)
		**out = **in
	}
	if in.SnapshotID != nil {
		in, out := &in.SnapshotID, &out.SnapshotID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserData != nil {
		in, out := &in.UserData, &out.UserData
		*out = new(string)
		**out = **in
	}
	if in.UserScheme != nil {
		in, out := &in.UserScheme, &out.UserScheme
		*out = new(string)
		**out = **in
	}
	if in.VPCIds != nil {
		in, out := &in.VPCIds, &out.VPCIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Vpc2Ids != nil {
		in, out := &in.Vpc2Ids, &out.Vpc2Ids
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceInitParameters.
func (in *InstanceInitParameters) DeepCopy() *InstanceInitParameters {
	if in == nil {
		return nil
	}
	out := new(InstanceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceList) DeepCopyInto(out *InstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Instance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceList.
func (in *InstanceList) DeepCopy() *InstanceList {
	if in == nil {
		return nil
	}
	out := new(InstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceObservation) DeepCopyInto(out *InstanceObservation) {
	*out = *in
	if in.ActivationEmail != nil {
		in, out := &in.ActivationEmail, &out.ActivationEmail
		*out = new(bool)
		**out = **in
	}
	if in.AllowedBandwidth != nil {
		in, out := &in.AllowedBandwidth, &out.AllowedBandwidth
		*out = new(float64)
		**out = **in
	}
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(float64)
		**out = **in
	}
	if in.AppVariables != nil {
		in, out := &in.AppVariables, &out.AppVariables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Backups != nil {
		in, out := &in.Backups, &out.Backups
		*out = new(string)
		**out = **in
	}
	if in.BackupsSchedule != nil {
		in, out := &in.BackupsSchedule, &out.BackupsSchedule
		*out = make([]BackupsScheduleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DateCreated != nil {
		in, out := &in.DateCreated, &out.DateCreated
		*out = new(string)
		**out = **in
	}
	if in.DdosProtection != nil {
		in, out := &in.DdosProtection, &out.DdosProtection
		*out = new(bool)
		**out = **in
	}
	if in.DisablePublicIPv4 != nil {
		in, out := &in.DisablePublicIPv4, &out.DisablePublicIPv4
		*out = new(bool)
		**out = **in
	}
	if in.Disk != nil {
		in, out := &in.Disk, &out.Disk
		*out = new(float64)
		**out = **in
	}
	if in.EnableIPv6 != nil {
		in, out := &in.EnableIPv6, &out.EnableIPv6
		*out = new(bool)
		**out = **in
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FirewallGroupID != nil {
		in, out := &in.FirewallGroupID, &out.FirewallGroupID
		*out = new(string)
		**out = **in
	}
	if in.GatewayV4 != nil {
		in, out := &in.GatewayV4, &out.GatewayV4
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.InternalIP != nil {
		in, out := &in.InternalIP, &out.InternalIP
		*out = new(string)
		**out = **in
	}
	if in.IpxeChainURL != nil {
		in, out := &in.IpxeChainURL, &out.IpxeChainURL
		*out = new(string)
		**out = **in
	}
	if in.IsoID != nil {
		in, out := &in.IsoID, &out.IsoID
		*out = new(string)
		**out = **in
	}
	if in.Kvm != nil {
		in, out := &in.Kvm, &out.Kvm
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.MainIP != nil {
		in, out := &in.MainIP, &out.MainIP
		*out = new(string)
		**out = **in
	}
	if in.NetmaskV4 != nil {
		in, out := &in.NetmaskV4, &out.NetmaskV4
		*out = new(string)
		**out = **in
	}
	if in.Os != nil {
		in, out := &in.Os, &out.Os
		*out = new(string)
		**out = **in
	}
	if in.OsID != nil {
		in, out := &in.OsID, &out.OsID
		*out = new(float64)
		**out = **in
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(string)
		**out = **in
	}
	if in.PowerStatus != nil {
		in, out := &in.PowerStatus, &out.PowerStatus
		*out = new(string)
		**out = **in
	}
	if in.RAM != nil {
		in, out := &in.RAM, &out.RAM
		*out = new(float64)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReservedIPID != nil {
		in, out := &in.ReservedIPID, &out.ReservedIPID
		*out = new(string)
		**out = **in
	}
	if in.SSHKeyIds != nil {
		in, out := &in.SSHKeyIds, &out.SSHKeyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ScriptID != nil {
		in, out := &in.ScriptID, &out.ScriptID
		*out = new(string)
		**out = **in
	}
	if in.ServerStatus != nil {
		in, out := &in.ServerStatus, &out.ServerStatus
		*out = new(string)
		**out = **in
	}
	if in.SnapshotID != nil {
		in, out := &in.SnapshotID, &out.SnapshotID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserData != nil {
		in, out := &in.UserData, &out.UserData
		*out = new(string)
		**out = **in
	}
	if in.UserScheme != nil {
		in, out := &in.UserScheme, &out.UserScheme
		*out = new(string)
		**out = **in
	}
	if in.V6MainIP != nil {
		in, out := &in.V6MainIP, &out.V6MainIP
		*out = new(string)
		**out = **in
	}
	if in.V6Network != nil {
		in, out := &in.V6Network, &out.V6Network
		*out = new(string)
		**out = **in
	}
	if in.V6NetworkSize != nil {
		in, out := &in.V6NetworkSize, &out.V6NetworkSize
		*out = new(float64)
		**out = **in
	}
	if in.VPCIds != nil {
		in, out := &in.VPCIds, &out.VPCIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.VcpuCount != nil {
		in, out := &in.VcpuCount, &out.VcpuCount
		*out = new(float64)
		**out = **in
	}
	if in.Vpc2Ids != nil {
		in, out := &in.Vpc2Ids, &out.Vpc2Ids
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceObservation.
func (in *InstanceObservation) DeepCopy() *InstanceObservation {
	if in == nil {
		return nil
	}
	out := new(InstanceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceParameters) DeepCopyInto(out *InstanceParameters) {
	*out = *in
	if in.ActivationEmail != nil {
		in, out := &in.ActivationEmail, &out.ActivationEmail
		*out = new(bool)
		**out = **in
	}
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(float64)
		**out = **in
	}
	if in.AppVariables != nil {
		in, out := &in.AppVariables, &out.AppVariables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Backups != nil {
		in, out := &in.Backups, &out.Backups
		*out = new(string)
		**out = **in
	}
	if in.BackupsSchedule != nil {
		in, out := &in.BackupsSchedule, &out.BackupsSchedule
		*out = make([]BackupsScheduleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DdosProtection != nil {
		in, out := &in.DdosProtection, &out.DdosProtection
		*out = new(bool)
		**out = **in
	}
	if in.DisablePublicIPv4 != nil {
		in, out := &in.DisablePublicIPv4, &out.DisablePublicIPv4
		*out = new(bool)
		**out = **in
	}
	if in.EnableIPv6 != nil {
		in, out := &in.EnableIPv6, &out.EnableIPv6
		*out = new(bool)
		**out = **in
	}
	if in.FirewallGroupID != nil {
		in, out := &in.FirewallGroupID, &out.FirewallGroupID
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.IpxeChainURL != nil {
		in, out := &in.IpxeChainURL, &out.IpxeChainURL
		*out = new(string)
		**out = **in
	}
	if in.IsoID != nil {
		in, out := &in.IsoID, &out.IsoID
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.OsID != nil {
		in, out := &in.OsID, &out.OsID
		*out = new(float64)
		**out = **in
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReservedIPID != nil {
		in, out := &in.ReservedIPID, &out.ReservedIPID
		*out = new(string)
		**out = **in
	}
	if in.SSHKeyIds != nil {
		in, out := &in.SSHKeyIds, &out.SSHKeyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ScriptID != nil {
		in, out := &in.ScriptID, &out.ScriptID
		*out = new(string)
		**out = **in
	}
	if in.SnapshotID != nil {
		in, out := &in.SnapshotID, &out.SnapshotID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserData != nil {
		in, out := &in.UserData, &out.UserData
		*out = new(string)
		**out = **in
	}
	if in.UserScheme != nil {
		in, out := &in.UserScheme, &out.UserScheme
		*out = new(string)
		**out = **in
	}
	if in.VPCIds != nil {
		in, out := &in.VPCIds, &out.VPCIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Vpc2Ids != nil {
		in, out := &in.Vpc2Ids, &out.Vpc2Ids
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceParameters.
func (in *InstanceParameters) DeepCopy() *InstanceParameters {
	if in == nil {
		return nil
	}
	out := new(InstanceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSpec) DeepCopyInto(out *InstanceSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSpec.
func (in *InstanceSpec) DeepCopy() *InstanceSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceStatus) DeepCopyInto(out *InstanceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceStatus.
func (in *InstanceStatus) DeepCopy() *InstanceStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceStatus)
	in.DeepCopyInto(out)
	return out
}
