// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/crossplane-contrib/provider-vultr/apis/namespaced/baremetal/v1alpha1"
	v1alpha1compute "github.com/crossplane-contrib/provider-vultr/apis/namespaced/compute/v1alpha1"
	v1alpha1database "github.com/crossplane-contrib/provider-vultr/apis/namespaced/database/v1alpha1"
	v1alpha1kubernetes "github.com/crossplane-contrib/provider-vultr/apis/namespaced/kubernetes/v1alpha1"
	v1alpha1loadbalancer "github.com/crossplane-contrib/provider-vultr/apis/namespaced/loadbalancer/v1alpha1"
	v1alpha1storage "github.com/crossplane-contrib/provider-vultr/apis/namespaced/storage/v1alpha1"
	v1alpha1namespaced "github.com/crossplane-contrib/provider-vultr/apis/namespaced/v1alpha1"
	v1beta1 "github.com/crossplane-contrib/provider-vultr/apis/namespaced/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1compute.SchemeBuilder.AddToScheme,
		v1alpha1database.SchemeBuilder.AddToScheme,
		v1alpha1kubernetes.SchemeBuilder.AddToScheme,
		v1alpha1loadbalancer.SchemeBuilder.AddToScheme,
		v1alpha1storage.SchemeBuilder.AddToScheme,
		v1alpha1namespaced.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
