// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ConnectionPool) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Database) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DB) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Replica) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}
